# Generated by Django 2.0.1 on 2018-01-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='color',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
