# Generated by Django 2.2 on 2019-04-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0006_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kasse.Menu', verbose_name='Menü')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='table_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kasse.TableSet'),
            preserve_default=False,
        ),
    ]
